### ISSUE TITLE
Importing the sprite file

### ISSUE THREAD

**Issue by ozcan-durak** [stevage/mbsprite#1]
Hi Steve

There isnt any specific docs to explain how to use the external generated sprite.json file with mapbox.

I have followed the https://docs.mapbox.com/mapbox-gl-js/style-spec/sprite/  but unable to do it.

If possible can you please share codepen sample. You are the only one i think who might guide us on this !

Thank you

**Comment by stevage** [comment]
Thanks for the comment! I've added some explicit instructions.
